DYNINST_ROOT=../Dyninst-8.2.1
DYNINST_IROOT=../Dyninst-8.2.1/install-dir
#DYNINST_ROOT=../Dyninst-9.0.3
#DYNINST_IROOT=../Dyninst-9.0.3/install-dir
#DYNINST_ROOT=../dyninst-mainline
#DYNINST_IROOT=../dyninst-mainline/install-dir
